### ISSUE TITLE
Handle namespace properly for path mapping

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumukit-platform#37]
If a base uri it's formed like: "adomain.com/base_path" and you want to generate the full url for "relative_path" for "a_tenant" it will result in: "adomain.com/a_tenant/base_path/relative_path" instead of "adomain.com/base_path/a_tenant/relative_path". 
Fixing this could make the implementation of `path_under_namespace?` cleaner.

**Comment by felipecalvo** [comment]
Fixed by https://github.com/mumuki/mumukit-platform/pull/39
